"""Offline demo mode for ResearchCrew.

Used when no Anthropic API key is configured. Produces a deterministic,
topic-aware canned research run so the web UI is fully interactive without
credentials. The shapes (ResearchPlan / ResearchFinding / ResearchReport) are
identical to the real agent outputs.
"""
from __future__ import annotations

from .config import settings
from .models import ResearchPlan, ResearchFinding, ResearchReport


def is_demo_mode() -> bool:
    """True when there is no usable Anthropic key (placeholder/empty)."""
    key = settings.anthropic_api_key.strip()
    return (not key) or key.startswith("sk-placeholder")


def demo_plan(topic: str) -> ResearchPlan:
    return ResearchPlan(
        topic=topic,
        sub_questions=[
            f"What is {topic} and why does it matter?",
            f"What are the core mechanisms behind {topic}?",
            f"What are the main limitations or open problems of {topic}?",
            f"What are the practical applications of {topic}?",
        ],
        scope=f"A moderate-depth overview of {topic} for a technical audience.",
        estimated_depth="moderate",
    )


def demo_finding(topic: str, sub_question: str) -> ResearchFinding:
    return ResearchFinding(
        sub_question=sub_question,
        key_points=[
            f"{topic} is an active area of research with growing industry adoption.",
            f"The sub-question '{sub_question[:60]}' is commonly approached from multiple angles.",
            "Recent work emphasises reproducibility, scalability, and evaluation rigor.",
            "Caveat: this is a demo response generated without an API key.",
        ],
        confidence="medium",
        limitations="Demo mode: points are illustrative, not sourced from a live model.",
    )


def demo_report(topic: str) -> ResearchReport:
    plan = demo_plan(topic)
    findings = [demo_finding(topic, q) for q in plan.sub_questions]
    return ResearchReport(
        title=f"{topic}: A Research Overview",
        executive_summary=(
            f"This report was generated by ResearchCrew in offline demo mode "
            f"(no ANTHROPIC_API_KEY configured). It demonstrates the full "
            f"planner → researcher → writer pipeline for the topic '{topic}'. "
            f"Configure an API key to run the real multi-agent system."
        ),
        findings=findings,
        conclusions=[
            f"{topic} spans both theoretical and applied research.",
            "The three-stage crew architecture (plan / research / synthesize) scales to any topic.",
            "Add an API key to upgrade from demo to live AI-driven research.",
        ],
        further_research=[
            "Provide an ANTHROPIC_API_KEY to enable real Claude-driven research.",
            "Integrate a retrieval tool (e.g. Tavily) for grounded, cited findings.",
        ],
        sources_note="Demo mode — no external sources consulted. Add an API key for live research.",
    )
